spring:
  application:
    name: spring-security-jpa

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres.pg/ssjb
#    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog.xml

server:
  ssl:
    enabled: true
    certificate: /app/cert/localhost.crt
    certificate-private-key: /app/cert/localhost.key
  port: 8443

management:
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
#    root: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG

app:
  jwt:
    secret: djkjhdgkjhdhgfkjaghdfkjasgdfkjhgasdkjfgas
    lifetime: 600000