apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-security-jpa-backend
  namespace: ssjb
  labels:
    app: ssjb
    rel: stable
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ssjb
  template:
    metadata:
      labels:
        app: ssjb
        rel: stable
    spec:
      containers:
        - name: ssjb-container
          image: spring-security-jpa-backend:v5
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: https-cert
              mountPath: /app/cert
              readOnly: true
            - name: tmp
              mountPath: /tmp
              readOnly: false
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              port: https
              path: /actuator/health/liveness
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: https
              path: /actuator/health/readiness
            initialDelaySeconds: 20
      restartPolicy: Always
      volumes:
        - name: https-cert
          secret:
            secretName: https-cert
        - name: tmp
          emptyDir: