apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-security-jpa-backend
  namespace: ssjb
  labels:
    app: ssjb
    rel: stable
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ssjb
  template:
    metadata:
      name: spring-security-jpa-backend
      labels:
        app: ssjb
        rel: stable
    spec:
      containers:
        - name: ssjb-container
          image: spring-security-jpa-backend
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 20
      restartPolicy: Always

