apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app: ssjb
      rel: stable
resources:
  - namespace.yaml
  - deployment.yaml
  - service-loadbalancer.yaml
secretGenerator:
  - name: https-cert
    namespace: ssjb
    options:
      immutable: true
    files:
      - ./certs/localhost.key
      - ./certs/localhost.crt