apiVersion: v1
kind: Service
metadata:
  name: spring-security-jpa-backend-lb
  namespace: ssjb
  labels:
    app: ssjb
    rel: stable
spec:
  sessionAffinity: None
  externalTrafficPolicy: Local
  selector:
    app: ssjb
    rel: stable
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: https
  type: LoadBalancer
  