apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app: pg
      rel: stable
resources:
  - namespace.yaml
  - secret-password.yaml
  - service-loadbalancer.yaml
  - stateful-set.yaml