apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-volume
  namespace: pg
spec:
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: /tmp/persvol