apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: pg
spec:
  type: LoadBalancer
  sessionAffinity: None
  selector:
    app: postgres
    rel: stable
  ports:
    - name: pgport
      protocol: TCP
      port: 5432
      targetPort: pgport
